FROM python:3.6.11-buster
MAINTAINER Full Bright <full3right@gmail.com>

WORKDIR /app/
COPY Pipfile /app/
RUN pip install pipenv
RUN pipenv --python 3.6

RUN pipenv install
CMD pipenv run python manage.py runserver 8001


