# Generated by Django 3.0.9 on 2020-08-31 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200830_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stock_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
