# Generated by Django 3.0.10 on 2020-10-31 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20201030_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='external_product_id',
            field=models.TextField(default=''),
        ),
    ]
