# Generated by Django 3.0.10 on 2020-10-31 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20201031_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='external_image',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
