# Generated by Django 3.0.10 on 2020-10-31 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20201031_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='external_product_id',
            field=models.CharField(max_length=256),
        ),
    ]
